---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: vue-frontend
          image: indhura/frontend-image
          ports:
            - containerPort: 80
