---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend-deployment.yaml
- frontend-deployment.yaml
- postgres-deployment.yaml
- backend-service.yaml
- frontend-service.yaml
- postgres-service.yaml
