apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: dev
data:
  DATABASE_URL: "postgres://postgres:password@myapp-dev-postgres-service:5432/people"
  NODE_ENV: "development"
  VUE_APP_API_URL: "http://myapp-dev-backend-service:3000"
  POSTGRES_DB: "mydatabase"
  API_URL: "http://myapp-dev-backend-service:3000" 
  # Add this key with the appropriate value
